comment_width = 80
group_imports = "StdExternalCrate"
imports_granularity = "Module"
max_width = 80
newline_style = "Unix"
normalize_comments = true
normalize_doc_attributes = true
reorder_impl_items = true
tab_spaces = 2
version = "Two"
wrap_comments = true
